// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config/model/model.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A Hat is a piece of headwear made by a Haberdasher.
type Hat struct {
	// The size of a hat should always be in inches.
	Size int32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// The color of a hat will never be 'invisible', but other than
	// that, anything is fair game.
	Color string `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	// The name of a hat is it's type. Like, 'bowler', or something.
	Name                  string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedOn             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	RgbColor              *Color               `protobuf:"bytes,5,opt,name=rgbColor,proto3" json:"rgbColor,omitempty"`
	AvailableSizes        []*Size              `protobuf:"bytes,6,rep,name=availableSizes,proto3" json:"availableSizes,omitempty"`
	Roles                 []int32              `protobuf:"varint,7,rep,packed,name=roles,proto3" json:"roles,omitempty"`
	Dictionary            map[string]int64     `protobuf:"bytes,8,rep,name=dictionary,proto3" json:"dictionary,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	DictionaryWithMessage map[string]*Size     `protobuf:"bytes,9,rep,name=dictionaryWithMessage,proto3" json:"dictionaryWithMessage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral  struct{}             `json:"-"`
	XXX_unrecognized      []byte               `json:"-"`
	XXX_sizecache         int32                `json:"-"`
}

func (m *Hat) Reset()         { *m = Hat{} }
func (m *Hat) String() string { return proto.CompactTextString(m) }
func (*Hat) ProtoMessage()    {}
func (*Hat) Descriptor() ([]byte, []int) {
	return fileDescriptor_1da357a4748065d8, []int{0}
}

func (m *Hat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hat.Unmarshal(m, b)
}
func (m *Hat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hat.Marshal(b, m, deterministic)
}
func (m *Hat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hat.Merge(m, src)
}
func (m *Hat) XXX_Size() int {
	return xxx_messageInfo_Hat.Size(m)
}
func (m *Hat) XXX_DiscardUnknown() {
	xxx_messageInfo_Hat.DiscardUnknown(m)
}

var xxx_messageInfo_Hat proto.InternalMessageInfo

func (m *Hat) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Hat) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Hat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Hat) GetCreatedOn() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedOn
	}
	return nil
}

func (m *Hat) GetRgbColor() *Color {
	if m != nil {
		return m.RgbColor
	}
	return nil
}

func (m *Hat) GetAvailableSizes() []*Size {
	if m != nil {
		return m.AvailableSizes
	}
	return nil
}

func (m *Hat) GetRoles() []int32 {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Hat) GetDictionary() map[string]int64 {
	if m != nil {
		return m.Dictionary
	}
	return nil
}

func (m *Hat) GetDictionaryWithMessage() map[string]*Size {
	if m != nil {
		return m.DictionaryWithMessage
	}
	return nil
}

type Color struct {
	Red                  int32    `protobuf:"varint,1,opt,name=red,proto3" json:"red,omitempty"`
	Green                int32    `protobuf:"varint,2,opt,name=green,proto3" json:"green,omitempty"`
	Blue                 int32    `protobuf:"varint,3,opt,name=blue,proto3" json:"blue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Color) Reset()         { *m = Color{} }
func (m *Color) String() string { return proto.CompactTextString(m) }
func (*Color) ProtoMessage()    {}
func (*Color) Descriptor() ([]byte, []int) {
	return fileDescriptor_1da357a4748065d8, []int{1}
}

func (m *Color) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Color.Unmarshal(m, b)
}
func (m *Color) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Color.Marshal(b, m, deterministic)
}
func (m *Color) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Color.Merge(m, src)
}
func (m *Color) XXX_Size() int {
	return xxx_messageInfo_Color.Size(m)
}
func (m *Color) XXX_DiscardUnknown() {
	xxx_messageInfo_Color.DiscardUnknown(m)
}

var xxx_messageInfo_Color proto.InternalMessageInfo

func (m *Color) GetRed() int32 {
	if m != nil {
		return m.Red
	}
	return 0
}

func (m *Color) GetGreen() int32 {
	if m != nil {
		return m.Green
	}
	return 0
}

func (m *Color) GetBlue() int32 {
	if m != nil {
		return m.Blue
	}
	return 0
}

type Receipt struct {
	Total                float64  `protobuf:"fixed64,1,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Receipt) Reset()         { *m = Receipt{} }
func (m *Receipt) String() string { return proto.CompactTextString(m) }
func (*Receipt) ProtoMessage()    {}
func (*Receipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_1da357a4748065d8, []int{2}
}

func (m *Receipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receipt.Unmarshal(m, b)
}
func (m *Receipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receipt.Marshal(b, m, deterministic)
}
func (m *Receipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receipt.Merge(m, src)
}
func (m *Receipt) XXX_Size() int {
	return xxx_messageInfo_Receipt.Size(m)
}
func (m *Receipt) XXX_DiscardUnknown() {
	xxx_messageInfo_Receipt.DiscardUnknown(m)
}

var xxx_messageInfo_Receipt proto.InternalMessageInfo

func (m *Receipt) GetTotal() float64 {
	if m != nil {
		return m.Total
	}
	return 0
}

// Size is passed when requesting a new hat to be made. It's always
// measured in inches.
type Size struct {
	Inches               int32    `protobuf:"varint,1,opt,name=inches,proto3" json:"inches,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Size) Reset()         { *m = Size{} }
func (m *Size) String() string { return proto.CompactTextString(m) }
func (*Size) ProtoMessage()    {}
func (*Size) Descriptor() ([]byte, []int) {
	return fileDescriptor_1da357a4748065d8, []int{3}
}

func (m *Size) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Size.Unmarshal(m, b)
}
func (m *Size) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Size.Marshal(b, m, deterministic)
}
func (m *Size) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Size.Merge(m, src)
}
func (m *Size) XXX_Size() int {
	return xxx_messageInfo_Size.Size(m)
}
func (m *Size) XXX_DiscardUnknown() {
	xxx_messageInfo_Size.DiscardUnknown(m)
}

var xxx_messageInfo_Size proto.InternalMessageInfo

func (m *Size) GetInches() int32 {
	if m != nil {
		return m.Inches
	}
	return 0
}

func init() {
	proto.RegisterType((*Hat)(nil), "config.model.Hat")
	proto.RegisterMapType((map[string]int64)(nil), "config.model.Hat.DictionaryEntry")
	proto.RegisterMapType((map[string]*Size)(nil), "config.model.Hat.DictionaryWithMessageEntry")
	proto.RegisterType((*Color)(nil), "config.model.Color")
	proto.RegisterType((*Receipt)(nil), "config.model.Receipt")
	proto.RegisterType((*Size)(nil), "config.model.Size")
}

func init() { proto.RegisterFile("config/model/model.proto", fileDescriptor_1da357a4748065d8) }

var fileDescriptor_1da357a4748065d8 = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xdf, 0x6b, 0xd4, 0x40,
	0x10, 0x26, 0xcd, 0xe5, 0xda, 0x9b, 0x8a, 0x96, 0xf5, 0x07, 0x21, 0x0f, 0x36, 0xde, 0x53, 0x1e,
	0x6c, 0x02, 0xf5, 0x45, 0x0b, 0x3e, 0x68, 0x15, 0x0e, 0x41, 0x84, 0x55, 0x10, 0x44, 0x28, 0x9b,
	0x64, 0x2e, 0xb7, 0xb8, 0xd9, 0x0d, 0x9b, 0xbd, 0xd6, 0xeb, 0xff, 0xe7, 0xff, 0x25, 0xbb, 0x9b,
	0xb6, 0xe9, 0x71, 0xfa, 0x12, 0xe6, 0xdb, 0xf9, 0xe6, 0xfb, 0x76, 0x32, 0xb3, 0x10, 0x57, 0x4a,
	0x2e, 0x79, 0x53, 0xb4, 0xaa, 0x46, 0xe1, 0xbf, 0x79, 0xa7, 0x95, 0x51, 0xe4, 0x81, 0xcf, 0xe4,
	0xee, 0x2c, 0x39, 0x6e, 0x94, 0x6a, 0x04, 0x16, 0x2e, 0x57, 0xae, 0x97, 0x85, 0xe1, 0x2d, 0xf6,
	0x86, 0xb5, 0x9d, 0xa7, 0xcf, 0xff, 0x4c, 0x20, 0x5c, 0x30, 0x43, 0x08, 0x4c, 0x7a, 0x7e, 0x8d,
	0x71, 0x90, 0x06, 0x59, 0x44, 0x5d, 0x4c, 0x9e, 0x40, 0x54, 0x29, 0xa1, 0x74, 0xbc, 0x97, 0x06,
	0xd9, 0x8c, 0x7a, 0x60, 0x99, 0x92, 0xb5, 0x18, 0x87, 0xee, 0xd0, 0xc5, 0xe4, 0x0d, 0x40, 0xa5,
	0x91, 0x19, 0xac, 0x2f, 0x94, 0x8c, 0x27, 0x69, 0x90, 0x1d, 0x9e, 0x26, 0xb9, 0xf7, 0xce, 0x6f,
	0xbc, 0xf3, 0x6f, 0x37, 0xde, 0x74, 0x36, 0xb0, 0xbf, 0x48, 0x52, 0xc0, 0x81, 0x6e, 0xca, 0x73,
	0xe7, 0x13, 0xb9, 0xc2, 0xc7, 0xf9, 0xb8, 0x85, 0xdc, 0xa5, 0xe8, 0x2d, 0x89, 0x9c, 0xc1, 0x43,
	0x76, 0xc9, 0xb8, 0x60, 0xa5, 0xc0, 0xaf, 0xfc, 0x1a, 0xfb, 0x78, 0x9a, 0x86, 0xd9, 0xe1, 0x29,
	0xb9, 0x5f, 0x66, 0x53, 0x74, 0x8b, 0x69, 0x3b, 0xd2, 0x4a, 0x60, 0x1f, 0xef, 0xa7, 0x61, 0x16,
	0x51, 0x0f, 0xc8, 0x3b, 0x80, 0x9a, 0x57, 0x86, 0x2b, 0xc9, 0xf4, 0x26, 0x3e, 0x70, 0x6a, 0x2f,
	0xee, 0xab, 0x2d, 0x98, 0xc9, 0x3f, 0xdc, 0x72, 0x3e, 0x4a, 0xa3, 0x37, 0x74, 0x54, 0x44, 0x4a,
	0x78, 0x7a, 0x87, 0xbe, 0x73, 0xb3, 0xfa, 0x8c, 0x7d, 0xcf, 0x1a, 0x8c, 0x67, 0x4e, 0xed, 0xe5,
	0xff, 0xd4, 0x46, 0x74, 0x2f, 0xbc, 0x5b, 0x2a, 0x79, 0x0b, 0x8f, 0xb6, 0xae, 0x40, 0x8e, 0x20,
	0xfc, 0x85, 0x1b, 0x37, 0xb4, 0x19, 0xb5, 0xa1, 0xed, 0xf0, 0x92, 0x89, 0x35, 0xba, 0x99, 0x85,
	0xd4, 0x83, 0xb3, 0xbd, 0xd7, 0x41, 0xf2, 0x13, 0x92, 0x7f, 0x7b, 0xee, 0x50, 0xca, 0xc6, 0x4a,
	0xbb, 0x7f, 0xef, 0x9d, 0xfa, 0xfc, 0x1c, 0x22, 0x3f, 0x9e, 0x23, 0x08, 0x35, 0xd6, 0xc3, 0x1e,
	0xd9, 0xd0, 0x5e, 0xa9, 0xd1, 0x88, 0xd2, 0x09, 0x45, 0xd4, 0x03, 0xbb, 0x46, 0xa5, 0x55, 0x0f,
	0xfd, 0xc2, 0xd9, 0x78, 0x7e, 0x0c, 0xfb, 0x14, 0x2b, 0xe4, 0x9d, 0xb1, 0x45, 0x46, 0x19, 0x26,
	0x9c, 0x50, 0x40, 0x3d, 0x98, 0x3f, 0x87, 0x89, 0x35, 0x26, 0xcf, 0x60, 0xca, 0x65, 0xb5, 0xc2,
	0x7e, 0xf0, 0x19, 0xd0, 0xfb, 0x4f, 0x3f, 0x16, 0x0d, 0x37, 0xab, 0x75, 0x99, 0x57, 0xaa, 0x2d,
	0x58, 0xd7, 0x19, 0x8d, 0xd8, 0xab, 0xa5, 0xb9, 0x62, 0x7a, 0x78, 0x04, 0xd5, 0x49, 0x83, 0xf2,
	0xc4, 0x5c, 0x71, 0xdd, 0x5d, 0xd4, 0x4c, 0x9b, 0x02, 0x7f, 0xb3, 0xb6, 0x13, 0x58, 0x34, 0xaa,
	0x18, 0x3f, 0xaa, 0x72, 0xea, 0xe8, 0xaf, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x61, 0xa7, 0x59,
	0x7f, 0x6b, 0x03, 0x00, 0x00,
}
